version: "3"

services:
  apache:
    image: httpd:2.4-alpine3.14
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/local/apache2/htdocs
      - ./docker-images/httpd:/usr/local/apache2/conf

  php:
    image: php:8.0-fpm
    volumes:
      - ./public:/usr/local/apache2/htdocs

  nodejs:
    image: node:17-alpine3.14
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app/nuxt
    working_dir: "/usr/app/nuxt"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command:
      - npm
      - run
      - dev
