version: "3"

services:
  nodejs:
    image: node:17-alpine3.14
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app/nuxt
    working_dir: "/usr/app/nuxt"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: npm run dev
